// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS7eS6BuEUGWBXqqgiafXIPgd0KK47EX0',
    appId: '1:850987377586:web:b8c57e7b3ffe7788407aab',
    messagingSenderId: '850987377586',
    projectId: 'foodray-95947',
    authDomain: 'foodray-95947.firebaseapp.com',
    storageBucket: 'foodray-95947.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd2ycBkc6dW41orDE8skB-WpLXzeLbvRg',
    appId: '1:850987377586:android:40e0ebbb02e657ef407aab',
    messagingSenderId: '850987377586',
    projectId: 'foodray-95947',
    storageBucket: 'foodray-95947.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVrQ1zJ3PDzX0syglhQYJ4b71KyKVmC7g',
    appId: '1:850987377586:ios:bc9fa50480c0a2d3407aab',
    messagingSenderId: '850987377586',
    projectId: 'foodray-95947',
    storageBucket: 'foodray-95947.firebasestorage.app',
    iosBundleId: 'com.example.foodray',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVrQ1zJ3PDzX0syglhQYJ4b71KyKVmC7g',
    appId: '1:850987377586:ios:bc9fa50480c0a2d3407aab',
    messagingSenderId: '850987377586',
    projectId: 'foodray-95947',
    storageBucket: 'foodray-95947.firebasestorage.app',
    iosBundleId: 'com.example.foodray',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS7eS6BuEUGWBXqqgiafXIPgd0KK47EX0',
    appId: '1:850987377586:web:679bf27a404095f9407aab',
    messagingSenderId: '850987377586',
    projectId: 'foodray-95947',
    authDomain: 'foodray-95947.firebaseapp.com',
    storageBucket: 'foodray-95947.firebasestorage.app',
  );
}
